apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ito1jej62-python 
  janus-idp.io/tekton: ito1jej62-python
  backstage.io/kubernetes-id: ito1jej62-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ito1jej62-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  